dist: trusty
language: go
go_import_path: github.com/coreos/zetcd
sudo: false

go:
  - 1.10.2

env:
  matrix:
   - TARGET=amd64

before_install:
 - go get -v -u honnef.co/go/tools/cmd/gosimple
 - go get -v -u honnef.co/go/tools/cmd/unused
 - go get -v -u honnef.co/go/tools/cmd/staticcheck
 - export GOROOT=$(go env GOROOT)

matrix:
  fast_finish: true

script:
 - make fmt
 - make test
